
service: golang-omie-serverless
frameworkVersion: '3'

provider:
  name: aws
  runtime: go1.x
  stage: stage, 'dev'

plugins:
  - serverless-offline

package:
  patterns:
    - '!./**'
    - ./bin/**

functions:
  listClients:
    handler: bin/internal/listClients
    events:
      - httpApi:
          path: /listClients
          method: post
  upSertClient:
    handler: bin/internal/upSertClient
    events:
      - httpApi:
          path: /upSertClient
          method: post
